---
- hosts: "{{ site }}"
  vars_files:
   - ../group_vars/all
  user: root
  tasks:
  - name: Create a new database with name "{{ dbname }}"
    mysql_db:
     name: "{{ dbname }}"
     login_user: root
     login_password: "{{ mysqlrootpassword }}"
     state: present

  - name: create mysql user "{{ dbusername }}"
    mysql_user:
     name: "{{ dbusername }}"
     password: "{{ dbpassword }}"
     priv: "{{ dbname }}.*:ALL"
     login_user: root
     login_password: "{{ mysqlrootpassword }}"
     state: present

  - name: Move wp-config-sample.php to wp-config.php
    template:
     src: ../templates/wp-config.php.j2
     dest: /var/www/html/{{ alias }}/wp-config.php
     owner: apache
     group: apache

  - name: Create backup dir /backup/{{ alias }}/
    file: path=/backup/{{ alias }}/ state=directory
  
  - name: Schedule db backups
    cron:
     name: "Schedule wordpress db backups"
     minute: "00"
     hour: "23"
     job: "mysqldump -u{{ dbusername }} -p{{ dbpassword }} --databases {{ dbname }} > /backup/{{ alias }}/{{ dbname }}.sql"
