---
- hosts: webserver 
  vars_files:
    - ../group_vars/all
  become: yes
  tasks:
  - name: Create /root/.aws config dir
    file: path=/root/.aws state=directory

  - name: set aws config at /root/.aws/config
    template:
     src: ../templates/aws/config.j2
     dest: /root/.aws/config

  - name: set aws config at /root/.aws/credentials
    template:
     src: ../templates/aws/credentials.j2
     dest: /root/.aws/credentials
