---
- hosts: webserver
  become: yes
  tasks:
  - name: Download latest Wordpress
    get_url:
     url: https://wordpress.org/latest.tar.gz
     dest: /opt/latest.tar.gz
     force: yes

  - name: Remove wordpress dir
    file:
     state: absent
     path: /opt/wordpress
  
  - name: Extract Wordpress tar.gz
    unarchive:
     remote_src: yes
     src: /opt/latest.tar.gz
     dest: /opt/
     owner: apache
     group: apache
