---
- hosts: webserver 
  become: yes
  tasks:
  - name: update yum cache
    command: yum makecache
  
  - name: install or upgrade Apache
    yum: name=httpd state=latest

  - name: install or upgrade MariaDB
    yum: name=mariadb-server state=latest

  - name: install or upgrade PHP
    yum: name=php state=latest

  - name: install or upgrade php-mysql
    yum: name=php-mysql state=latest

  - name: install or upgrade php-gd
    yum: name=php-gd state=latest

  - name: install or upgrade vim
    yum: name=vim state=latest

  - name: install or upgrade wget
    yum: name=wget state=latest
  
  - name: install or upgrade unzip
    yum: name=unzip state=latest

  - name: install or upgrade mysql-python
    yum: name=MySQL-python state=latest

  - name: Download pip
    get_url:
     url: https://bootstrap.pypa.io/get-pip.py
     dest: /opt/

  - name: Install pip
    shell: python /opt/get-pip.py

  - name: Install awscli
    shell: pip install awscli --upgrade
