---
- hosts: webserver 
  vars_files:
    - ../group_vars/all
  become: yes
  tasks:
  - name: Set root user password
    mysql_user: name=root
              host="localhost"
              password="{{ mysqlrootpassword }}"
              check_implicit_admin=yes
              login_user="root"
              state=present
