---
- hosts: webserver 
  user: root
  tasks:
  - name: Restart httpd
    service:
     name: httpd
     state: restarted
     enabled: yes

  - name: Restart mariadb
    service:
     name: mariadb
     state: restarted
     enabled: yes
